// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// distX
NumericVector distX(NumericMatrix x, int nr, int nc);
RcppExport SEXP _densityratio_distX(SEXP xSEXP, SEXP nrSEXP, SEXP ncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    rcpp_result_gen = Rcpp::wrap(distX(x, nr, nc));
    return rcpp_result_gen;
END_RCPP
}
// distXY
NumericMatrix distXY(NumericMatrix x, NumericMatrix y, int nrx, int nry, int nc);
RcppExport SEXP _densityratio_distXY(SEXP xSEXP, SEXP ySEXP, SEXP nrxSEXP, SEXP nrySEXP, SEXP ncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nrx(nrxSEXP);
    Rcpp::traits::input_parameter< int >::type nry(nrySEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    rcpp_result_gen = Rcpp::wrap(distXY(x, y, nrx, nry, nc));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_densityratio_distX", (DL_FUNC) &_densityratio_distX, 3},
    {"_densityratio_distXY", (DL_FUNC) &_densityratio_distXY, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_densityratio(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
