# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a Gram matrix with squared Euclidean distances between
#' observations in the input matrix \code{X} and the input matrix \code{Y}
#' @param X A numeric input matrix
#' @param Y A numeric input matrix with the same variables as \code{X}
#' @param symmetric A logical indicating whether X and Y are the same
NULL

distance <- function(X, Y, symmetric = FALSE) {
    .Call(`_densityratio_distance`, X, Y, symmetric)
}

kernel_gaussian <- function(dist, sigma) {
    .Call(`_densityratio_kernel_gaussian`, dist, sigma)
}

#' Perform QR decomposition of the input matrix \code{X} through householder
#' transformations, similar to Matlab's QR decomposition.
#'
#' @param X A numeric matrix.
NULL

householder_QR <- function(X) {
    .Call(`_densityratio_householder_QR`, X)
}

make_Phi <- function(dist_nu, sigma) {
    .Call(`_densityratio_make_Phi`, dist_nu, sigma)
}

make_phibar <- function(dist_de, sigma) {
    .Call(`_densityratio_make_phibar`, dist_de, sigma)
}

kliep_compute_alpha <- function(Phi, phibar, phibar_corr, epsilon, nepsilon, maxit, progressbar) {
    .Call(`_densityratio_kliep_compute_alpha`, Phi, phibar, phibar_corr, epsilon, nepsilon, maxit, progressbar)
}

compute_kliep <- function(dist_nu, dist_de, sigma, epsilon, maxit, cv_ind, progressbar) {
    .Call(`_densityratio_compute_kliep`, dist_nu, dist_de, sigma, epsilon, maxit, cv_ind, progressbar)
}

ulsif_compute_alpha <- function(Hhat, hhat, lambda) {
    .Call(`_densityratio_ulsif_compute_alpha`, Hhat, hhat, lambda)
}

set_threads <- function(nthreads) {
    .Call(`_densityratio_set_threads`, nthreads)
}

compute_ulsif_loocv <- function(Hhat, hhat, lambda, nnu, nde, nmin, ncol, Knu_nmin, Kde_nmin) {
    .Call(`_densityratio_compute_ulsif_loocv`, Hhat, hhat, lambda, nnu, nde, nmin, ncol, Knu_nmin, Kde_nmin)
}

compute_ulsif <- function(dist_nu, dist_de, sigma, lambda, parallel, nthreads, progressbar) {
    .Call(`_densityratio_compute_ulsif`, dist_nu, dist_de, sigma, lambda, parallel, nthreads, progressbar)
}

