# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a Gram matrix with squared Euclidean distances between
#' observations in the input matrix \code{X} and the input matrix \code{Y}
#' @param X A numeric input matrix
#' @param Y A numeric input matrix with the same variables as \code{X}
#' @param symmetric A logical indicating whether X and Y are the same
NULL

distance <- function(X, Y, symmetric = FALSE) {
    .Call(`_densityratio_distance`, X, Y, symmetric)
}

#' Perform QR decomposition of the input matrix \code{X} through householder
#' transformations, similar to Matlab's QR decomposition.
#'
#' @param X A numeric matrix.
NULL

householder_QR <- function(X) {
    .Call(`_densityratio_householder_QR`, X)
}

compute_ulsif <- function(Hhat, hhat, lambda, parallel, nthreads) {
    .Call(`_densityratio_compute_ulsif`, Hhat, hhat, lambda, parallel, nthreads)
}

