# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a Gram matrix with squared Euclidean distances between all
#' observations in the input matrix
#'
#' @param x A numeric input matrix
#' @param nr Number of rows of the input matrix
#' @param nc Number of columns of the input matrix
#' @export
distX <- function(x, nr, nc) {
    .Call(`_densityratio_distX`, x, nr, nc)
}

#' Create a Gram matrix with squared Euclidean distances between
#' observations in the input matrix x and the input matrix y
#' @param x A numeric input matrix
#' @param y A numeric input matrix with the same variables as x
#' @param nrx Number of rows of the input matrix x
#' @param nry Number of rows of the input matrix y
#' @param nc Number of columns of the input matrices x and y
#' @export
distXY <- function(x, y, nrx, nry, nc) {
    .Call(`_densityratio_distXY`, x, y, nrx, nry, nc)
}

